AWSTemplateFormatVersion: '2010-09-09'
Description: Smart VPN Server with monitoring usage and alert
Parameters:
  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 instance type

  ExistingKeyPairName:
    Type: AWS::EC2::KeyPair::KeyName

  UserName:
    Type: String
    Description: vpn management

  Password:
    Type: String
    Description: vpn management
    NoEcho: true

  AlertEmail:
    Type: String

  DuckDnsDomain:
    Type: String
    Description: DuckDNS subdomain(without .duckdns.org)

  DuckDnsToken:
    Type: String
    NoEcho: true

Resources:
  # Networking
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAccosication:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref Subnet

  WireGuardSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for WireGuard VPN Server
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: udp
          FromPort: 51820
          ToPort: 51820
          CidrIp: 0.0.0.0/0
          Description: WireGuard VPN
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: SSH
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  WireGuardInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        - PolicyName: WireGuardInstancePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:StopInstances
                  - ec2:StartInstances
                  - cloudwatch:PutMetricData
                  - cloudwatch:GetMetricStatistics
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - ssm:SendCommand
                  - ssm:GetCommandInvocation
                Resource: '*'

  WireGuardInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref WireGuardInstanceRole

  WireGuardInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64}}'
      InstanceType: !Ref InstanceType
      KeyName: !Ref ExistingKeyPairName
      IamInstanceProfile: !Ref WireGuardInstanceProfile
      SecurityGroupIds:
        - !Ref WireGuardSecurityGroup
      SubnetId: !Ref Subnet
      UserData: !Base64
        Fn::Sub: |
          Content-Type: multipart/mixed; boundary="//"
          MIME-Version: 1.0
            
          --//
          Content-Type: text/x-shellscript-per-boot; charset="us-ascii"
          MIME-Version: 1.0
          Content-Transfer-Encoding: 7bit
          Content-Disposition: attachment; filename="per-boot.txt"

          #!/bin/bash
          date >> boot-history
          curl -s "https://www.duckdns.org/update?domains=${DuckDnsDomain}&token=${DuckDnsToken}&ip="
            
          --//
          Content-Type: text/x-shellscript; charset="us-ascii"
          MIME-Version: 1.0
          Content-Transfer-Encoding: 7bit
          Content-Disposition: attachment; filename="userdata.txt"

          #!/bin/bash

          dnf update -y
          dnf install -y --skip-broken wireguard-tools iptables-services curl amazon-ssm-agent

          systemctl enable amazon-ssm-agent --now

          # Enable IP forwarding
          echo 'net.ipv4.ip_forward = 1' >> /etc/sysctl.conf
          echo 'net.ipv6.conf.all.forwarding = 1' >> /etc/sysctl.conf
          sysctl -p

          mkdir -p /etc/wireguard
          cd /etc/wireguard
          umask 077

          wg genkey | tee server.key | wg pubkey > server.pub
          for i in 1 2 3; do
            wg genkey |tee client$i.key | wg pubkey > client$i.pub
          done

          cat > wg0.conf <<EOF
          [Interface]
          Address = 10.8.0.1/24, fd42:42:42::1/64
          ListenPort = 51820
          PrivateKey = $(cat server.key)

          PostUp = iptables -A FORWARD -i wg0 -j ACCEPT
          PostUp = iptables -A FORWARD -o wg0 -j ACCEPT
          PostUp = iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j MASQUERADE

          PostUp = ip6tables -A FORWARD -i wg0 -j ACCEPT
          PostUp = ip6tables -A FORWARD -o wg0 -j ACCEPT
          PostUp = ip6tables -t nat -A POSTROUTING -s fd42:42:42::/64 -j MASQUERADE
          EOF

          for i in 1 2 3; do
          cat >> wg0.conf <<EOF

          [Peer]
          PublicKey = $(cat client$i.pub)
          AllowedIPs = 10.8.0.$((i+1))/32, fd42:42:42::$((i+1))/128
          EOF
          done

          systemctl enable wg-quick@wg0 --now

          curl -s "https://www.duckdns.org/update?domains=${DuckDnsDomain}&token=${DuckDnsToken}&ip="
          --//--         
  # db for sessions
  SessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true

  MetricsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true

  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: email
          Endpoint: !Ref AlertEmail

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: VpnControl
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:StartInstances
                  - ec2:StopInstances
                  - ec2:DescribeInstances
                  - cloudwatch:GetMetricStatistics
                  - sns:Publish
                  - ssm:SendCommand
                  - ssm:GetCommandInvocation
                Resource: '*'
              - Effect: Allow
                Action: dynamodb:*
                Resource: '*'
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${VPNManagementFunction}
      RetentionInDays: 30

  VPNManagementFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.12
      Handler: index.handler
      Timeout: 60
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          ADMIN_USER: !Ref UserName
          ADMIN_PASS: !Ref Password
          SESSION_TABLE: !Ref SessionTable
          METRICS_TABLE: !Ref MetricsTable
          INSTANCE_ID: !Ref WireGuardInstance
          ALERT_TOPIC: !Ref AlertTopic
      
  # API Gateway
  VPNManagementAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${AWS::StackName}-vpn-management
      Description: Smart VPN Server Management API

  VPNManagementResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref VPNManagementAPI
      ParentId: !GetAtt VPNManagementAPI.RootResourceId
      PathPart: '{proxy+}'
    
  VPNManagementMethodRoot:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref VPNManagementAPI
      ResourceId: !GetAtt VPNManagementAPI.RootResourceId
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${VPNManagementFunction.Arn}/invocations

  VPNManagementMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref VPNManagementAPI
      ResourceId: !Ref VPNManagementResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${VPNManagementFunction.Arn}/invocations

  VPNManagementDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: 
      - VPNManagementMethodRoot
      - VPNManagementMethod
    Properties:
      RestApiId: !Ref VPNManagementAPI
      StageName: prod

  # Lambda Permission for API Gateway
  VPNManagementLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref VPNManagementFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${VPNManagementAPI}/*

  # EventBridge Rule for Daily Check
  VPNDailyCheckRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Daily VPN traffic check and auto-shutdown
      ScheduleExpression: !Sub cron(0 15 * * ? *) # 22:00 Hong Kong time (UTC+8)
      State: ENABLED
      Targets:
        - Arn: !GetAtt VPNManagementFunction.Arn
          Id: VPNDailyCheck
          Input: '{"queryStringParameters": {"action": "check_traffic"}}'

  VPNDailyCheckPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref VPNManagementFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt VPNDailyCheckRule.Arn

Outputs:
  VPNManagementURL:
    Description: ðŸŒ Static web endpoint to manage your VPN server
    Value: !Sub https://${VPNManagementAPI}.execute-api.${AWS::Region}.amazonaws.com/prod
    Export:
      Name: !Sub ${AWS::StackName}-Management-URL

  VPNServerPublicIP:
    Description: ðŸ“ Current VPN server public IP (dynamic)
    Value: !GetAtt WireGuardInstance.PublicIp